name: build-release

on:
  push:
    tags: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-aarch64-macos:
    uses: ./.github/workflows/_prebuild-v8.yml
    with:
      runner: macos-26
      target: aarch64-macos
      build_type: release
  
  release:
    needs: build-aarch64-macos
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: aarch64-macos
          path: dist

      - name: Create/update release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
